// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgSAgWxdGmhpZi5cWPp4IZt-Au_OwKUY',
    appId: '1:71292641552:web:616bea8dcbdf2f86c40595',
    messagingSenderId: '71292641552',
    projectId: 'bookmyclinic-5f034',
    authDomain: 'bookmyclinic-5f034.firebaseapp.com',
    storageBucket: 'bookmyclinic-5f034.appspot.com',
    measurementId: 'G-J1PMCR30P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDcJWcNo0_lpxs6003n8PqxhXUkZUItY',
    appId: '1:71292641552:android:587f44964dcc8966c40595',
    messagingSenderId: '71292641552',
    projectId: 'bookmyclinic-5f034',
    storageBucket: 'bookmyclinic-5f034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjtUFZwzuz9F0H4_F8yvW-nfapE5dXFqA',
    appId: '1:71292641552:ios:49749a292d32c35dc40595',
    messagingSenderId: '71292641552',
    projectId: 'bookmyclinic-5f034',
    storageBucket: 'bookmyclinic-5f034.appspot.com',
    iosBundleId: 'com.example.bookMyClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjtUFZwzuz9F0H4_F8yvW-nfapE5dXFqA',
    appId: '1:71292641552:ios:cbba5922e2d27c22c40595',
    messagingSenderId: '71292641552',
    projectId: 'bookmyclinic-5f034',
    storageBucket: 'bookmyclinic-5f034.appspot.com',
    iosBundleId: 'com.example.bookMyClinic.RunnerTests',
  );
}
